version: "3.9"

networks:
  web:
    external: true

services:
  php_example_com:
    image: php:8.2-fpm
    container_name: php_example_com
    restart: unless-stopped
    networks:
      - web
    working_dir: /var/www/html
    volumes:
      # Код сайта
      - ./www:/var/www/html:rw
      # Конфиги php-fpm для этого сайта
      - ../../config/php-fpm/example.com/php.ini:/usr/local/etc/php/conf.d/site.ini:ro
      - ../../config/php-fpm/example.com/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro

